DELETE http://localhost:3003/api/blogs/660159f2af1cfb0eb40d8d2e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdvZCIsImlkIjoiNjYwMTVjMWViMzg0MzI1YjYwN2U1ZjYwIiwiaWF0IjoxNzExMzY1NzQzLCJleHAiOjE3MTEzNjkzNDN9.90gpWQrIYPxPJdZjOeNbc8nGaAfDJINrB4I7U8nEFW4